language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install git+git://github.com/ojii/pymaging.git#egg=pymaging
  - pip install git+git://github.com/ojii/pymaging-png.git#egg=pymaging-png
  - pip install -r requirements.txt
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test